import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <h1 style={{display : 'inline'}}><Link href="/">Low Price</Link></h1>
      <h3 style={{display : 'inline', margin: '3px' }}>Apple</h3>
      <main>{children}</main>
      <h5>이 포스팅은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받을 수 있습니다.</h5>
    </>
  )
}
